"""
Django settings for bank project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import environ


from django.templatetags.static import static
from django.urls import reverse_lazy
from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
env = environ.Env()

environ.Env.read_env(os.path.join(BASE_DIR,'file.env'))


# settings.py
SESSION_EXPIRE_AT_BROWSER_CLOSE = True


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@^^&_3r$p1tr#jxmb#nx3q*oi#wo%bxr!x^n(a%61pu@=#jq%3'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

# ALLOWED_HOSTS = ["*"]
CSRF_TRUSTED_ORIGINS = ["https://belcoccu.com"]
ALLOWED_HOSTS = ["belcoccu.com"]



# Application definition
AUTH_USER_MODEL = 'bank_app.Account'

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.filters",
    "unfold.contrib.import_export",
    "unfold.contrib.guardian",
    "unfold.contrib.simple_history",
    "unfold.contrib.forms", 
    "unfold.contrib.inlines",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    "django_extensions",
    'import_export',
    'bank_app',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'bank.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR,'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'bank.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DB_NAME'),  
        'USER': env('DB_USER'),
        'PASSWORD': env('DB_PASSWORD'),
        'HOST': env('DB_HOST'),
        'PORT': env('DB_PORT'),
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
MEDIA_URL = '/media/'



# if DEBUG:
STATICFILES_DIRS = [os.path.join(BASE_DIR,'static')]
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
# else:
STATIC_ROOT = os.path.join(BASE_DIR,'staticfiles')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.zoho.com'
EMAIL_PORT = 465
EMAIL_USE_TLS = False
EMAIL_USE_SSL = True
EMAIL_HOST_USER = env('EMAIL_HOST_USER')  
EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = 'info@belcoccu.com'




# Unfold configuration
UNFOLD = {
    "SITE_HEADER": "Belco Community Credit Union",
    "SITE_TITLE": "Belco Community Credit Union",
    "SITE_SUBHEADER": "Belco Community Credit Union",
    "SITE_URL": "/",
    "SHOW_SIDEBAR": True,
    "SITE_ICON": {
        "light": lambda request: static("images/Belco_logo.png"),
        "dark": lambda request: static("images/logo_white.png"),
    },
    "SITE_LOGO": {
        "light": lambda request: static("images/Belco_logo.png"),
        "dark": lambda request: static("images/logo_white.png"),
    },
    "DASHBOARD": {
        "show_search": True,
        "show_all_applications": True,
        "cards": [
            {
                "title": _("Users"),
                "icon": "group",
                "link": reverse_lazy("admin:bank_app_account_changelist"),
                "description": _("Manage users in the system."),
            },
            {
                "title": _("Deposits"),
                "icon": "account_balance",
                "link": reverse_lazy("admin:bank_app_deposit_changelist"),
                "description": _("Manage deposits."),
            },
            {
                "title": _("Transfers"),
                "icon": "swap_horiz",
                "link": reverse_lazy("admin:bank_app_transfer_changelist"),
                "description": _("Manage transfers."),
            },
            {
                "title": _("Transactions"),
                "icon": "receipt",
                "link": reverse_lazy("admin:bank_app_transaction_changelist"),
                "description": _("Manage transactions."),
            },
            {
                "title": _("Beneficiaries"),
                "icon": "person_add",
                "link": reverse_lazy("admin:bank_app_beneficiary_changelist"),
                "description": _("Manage beneficiaries for transfers."),
            },
            {
                "title": _("Reset Passwords"),
                "icon": "lock_reset",
                "link": reverse_lazy("admin:bank_app_resetpassword_changelist"),
                "description": _("Manage password reset requests."),
            },
        ],
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": _("Menu"),
                "icon": "account_circle",
                "collapsible": False,
                "items": [
                    {
                        "title": _("Users"),
                        "icon": "group",
                        "link": reverse_lazy("admin:bank_app_account_changelist"),
                    },
                    {
                        "title": _("Account Balances"),
                        "icon": "account_balance_wallet",
                        "link": reverse_lazy("admin:bank_app_accountbalance_changelist"),
                    },
                    {
                        "title": _("Currency Balances"),
                        "icon": "currency_exchange",
                        "link": reverse_lazy("admin:bank_app_currencybalance_changelist"),
                    },
                ],
            },
            {
                "title": _("Banking & Cards"),
                "icon": "credit_card",
                "collapsible": False,
                "separator": True,
                "items": [
                    {
                        "title": _("Cards"),
                        "icon": "credit_card",
                        "link": reverse_lazy("admin:bank_app_card_changelist"),
                    },
                    {
                        "title": _("Deposits"),
                        "icon": "account_balance",
                        "link": reverse_lazy("admin:bank_app_deposit_changelist"),
                    },
                    {
                        "title": _("Transfers"),
                        "icon": "swap_horiz",
                        "link": reverse_lazy("admin:bank_app_transfer_changelist"),
                    },
                    # {
                    #     "title": _("Transfer Codes"),
                    #     "icon": "code",
                    #     "link": reverse_lazy("admin:bank_app_transfercode_changelist"),
                    # },
                    {
                        "title": _("Beneficiaries"),
                        "icon": "person_add",
                        "link": reverse_lazy("admin:bank_app_beneficiary_changelist"),
                    },
                ],
            },
            {
                "title": _("Finances"),
                "icon": "attach_money",
                "collapsible": True,
                "separator": True,
                "items": [
                    {
                        "title": _("Exchanges"),
                        "icon": "currency_exchange",
                        "link": reverse_lazy("admin:bank_app_exchange_changelist"),
                    },
                    {
                        "title": _("Exchange Rates"),
                        "icon": "bar_chart",
                        "link": reverse_lazy("admin:bank_app_exchangerate_changelist"),
                    },
                    {
                        "title": _("Loan Requests"),
                        "icon": "request_quote",
                        "link": reverse_lazy("admin:bank_app_loanrequest_changelist"),
                    },
                    {
                        "title": _("Payment Gateways"),
                        "icon": "payment",
                        "link": reverse_lazy("admin:bank_app_paymentgateway_changelist"),
                    },
                    {
                        "title": _("Transactions"),
                        "icon": "receipt",
                        "link": reverse_lazy("admin:bank_app_transaction_changelist"),
                    },
                    # {
                    #     "title": _("Reset Passwords"),
                    #     "icon": "lock_reset",
                    #     "link": reverse_lazy("admin:bank_app_resetpassword_changelist"),
                    # },
                ],
            },
        ],
    },
}
