# Generated by Django 5.0.7 on 2025-08-13 09:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checking_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Checking account balance in USD.', max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('savings_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Savings account balance in USD.', max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('credit_balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Outstanding credit balance in USD (e.g., credit card debt).', max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CurrencyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('GBP', 'British Pound'), ('EUR', 'Euro')], max_length=3)),
                ('balance_type', models.CharField(choices=[('CHECKING', 'Checking'), ('SAVINGS', 'Savings'), ('CREDIT', 'Credit')], max_length=10)),
                ('balance', models.DecimalField(decimal_places=2, default=0.0, help_text='Balance for the specified currency and account type.', max_digits=12, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('account_balance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_balances', to='bank_app.accountbalance')),
            ],
            options={
                'unique_together': {('account_balance', 'currency', 'balance_type')},
            },
        ),
    ]
