# Generated by Django 5.0.7 on 2025-08-13 09:26

import bank_app.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0002_accountbalance_currencybalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('credit', 'Credit'), ('debit', 'Debit'), ('prepaid', 'Prepaid')], default='debit', max_length=20)),
                ('vendor', models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'MasterCard'), ('amex', 'American Express'), ('discover', 'Discover')], default='visa', max_length=20)),
                ('account', models.CharField(blank=True, help_text='16-digit card number', max_length=16, null=True, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('blocked', 'Blocked')], default='active', max_length=20)),
                ('card_password', models.CharField(blank=True, help_text='4-digit PIN for the card (store securely in production)', max_length=4, null=True)),
                ('expiry_date', models.DateField(default=bank_app.models.default_expiry_date, help_text='Expiry date (2 years from creation)')),
                ('balance_type', models.CharField(choices=[('CHECKING', 'Checking'), ('SAVINGS', 'Savings'), ('CREDIT', 'Credit')], default='CHECKING', help_text='Balance type this card is linked to (e.g., checking for debit, credit for credit card)', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
