# Generated by Django 5.0.7 on 2025-08-13 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0004_exchangerate_paymentgateway_resetpassword_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='vendor',
            field=models.CharField(choices=[('visa', 'Visa'), ('mastercard', 'MasterCard'), ('amex', 'American Express'), ('discover', 'Discover')], default='mastercard', max_length=20),
        ),
    ]
