# Generated by Django 5.0.7 on 2025-08-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0005_alter_card_vendor'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, default='assets/images/avatar/default_profile.png', help_text='Profile picture (min 300x300, max 5MB, GIFs allowed).', null=True, upload_to='profile_pics/'),
        ),
    ]
