# Generated by Django 5.0.7 on 2025-08-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0006_account_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_picture',
            field=models.ImageField(blank=True, default='profile_pics/default_profile.png', help_text='Profile picture (min 300x300, max 5MB, GIFs allowed).', null=True, upload_to='profile_pics/'),
        ),
    ]
