# Generated by Django 5.0.7 on 2025-08-21 19:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0008_alter_deposit_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
