# Generated by Django 5.0.7 on 2025-09-11 15:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0009_alter_transfer_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='security_code',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(100000, message='Security code must be at least 100000.'), django.core.validators.MaxValueValidator(999999, message='Security code must be at most 999999.')]),
        ),
    ]
