# Generated by Django 5.0.7 on 2025-09-13 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0010_account_security_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='cot_code',
        ),
        migrations.RemoveField(
            model_name='account',
            name='imf_code',
        ),
        migrations.RemoveField(
            model_name='account',
            name='tax_code',
        ),
    ]
