# Generated by Django 5.0.7 on 2025-09-13 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0011_remove_account_cot_code_remove_account_imf_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='two_factor_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
