# Generated by Django 5.0.7 on 2025-09-14 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0012_account_two_factor_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='date_joined',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date Joined'),
        ),
    ]
